# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LearnRxSwift_Moya' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearnRxSwift_Moya
  pod 'Moya/RxSwift', '~> 15.0'

end
